name: CI
concurrency: ci-${{ github.ref }}

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:   
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: NPM install
      run: npm install
    - run: npm ci
    - run: npm run lint:style
    - run: npm run lint:js
    - run: npm test
