name: CI
concurrency: ci-${{ github.ref }}

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:   
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: NPM install
      run: npm ci

    - name: NPM test
      run: npm test

  build:
    needs: test
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        test:
          - linux
          - macos
          - windows
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: NPM install
      run: npm ci

    - name: NPM build
      run: npm run build:${{matrix.test}}
